class AppState:
    WELCOME = "WELCOME"
    DEPARTMENT = "DEPARTMENT"
    CATEGORY = "CATEGORY"
    CATALOGUE = "CATALOGUE"
    PRODUCT_DETAIL = "PRODUCT_DETAIL"
    CAMERA_WARNING = "CAMERA_WARNING"
    MAP = "MAP"
    TRY_ON = "TRY_ON"